# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(null=True, verbose_name=b'date completed'),
        ),
    ]
